### ISSUE TITLE
Windows 10 + WordPress - can't connect via SSH

### ISSUE THREAD

**Issue by vyskoczilova** [spatie/ray#482]
**Describe the bug**

I add the server details into the ray app, click to connect and it ends with "Ray was unable to bind to the remote server's port. Is the port in use or is someone else using Ray on this server"?

**Versions**
Ray version (you can see this in "About Ray"): 1.15.0.0
PHP version: 7.4

**To Reproduce**
Try to connect to the WP Engine SSH server.

**Expected behavior**
Connect.

**Screenshots**
![image](https://user-images.githubusercontent.com/3611726/123081453-4237e980-d41e-11eb-85ae-fbc5f1537df2.png)
https://www.loom.com/share/b93be68ea06d4eaaad27eca8e6ad8a6b

**Desktop (please complete the following information):**
- OS: Windows 10 PRO
- Version: 21H1(build 19043.1052)
 
 **Additional context**

The port & connection works, tested from the command line. Ray plugin is installed. However, I have ssh access only to the root of the server and the WP site is in the "sites" directory. This is probably pretty common for many server installations so I believe this shouldn't be a problem.

I'm trying to connect to WP Engine hosting (a premium WP hosting service).

I wanted to buy the app just for those ssh debugs, but still not able to make it work.

**Comment by AdrianMrn** [comment]
SSH port binding/forwarding might be disabled in WP Engine. Could you try the following steps? You might need to use `ssh` instead of `plink` for this to work.

1. Open Ray, go to your preferences and make sure the port is set to 23517
2. Run `ssh -R 23517:localhost:23517 bigdatadev@bigdatadev.ssh.wpengine.net`

If this doesn't work, WP Engine most likely doesn't support SSH tunnels, which is what we use to connect to remote servers in Ray.
