### ISSUE TITLE
Tweak your docs for setting up Ray with docker on Ubuntu

### ISSUE THREAD

**Issue by nijlandvpr** [spatie/ray#530]
**Describe the issue**
I could not get anything to display in Ray after initial installation. Here's the situation (and the fix).

**Versions**
Ray version (you can see this in "About Ray"): 1.16.0
spatie/ray package version: 1.29.0
spatie/laravel-ray package version (if applicable): 1.24.2
PHP version: 8.0.8
Laravel version (if applicable): 8.52.0
Docker version: 20.10.7

**To Reproduce**
1. install the appimage
2. composer require
3. publish the config with the --docker tag
4. edit the docker-compose.yml and add "extra_hosts" and "host.docker.internal:host-gateway" to the nginx service
5. add RAY_ENABLE=true, RAY_HOST=host.docker.internal, RAY_REMOTE_PATH=absolute in container, RAY_LOCAL_PATH=absolute local to volume mount
6. add ray('Hello'); to code
7. run the app

**Expected behavior**
Nothing is displayed in Ray.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version 20.04
 
 **Additional context**
The docker environment creates individual containers for each service.

**The fix**
Add "extra_hosts" to the **php-fpm service** (it was added to all services, but this one made the difference)

**Comment by AdrianMrn** [comment]
Hi @nijlandvpr, I can't immediately find the section where this should be added, since I don't have much experience with Linux and Docker 🙈  Are you talking about the `services` code block at the bottom of this page? https://github.com/spatie/ray/blob/main/docs/environment-specific-configuration/docker.md

If you'd like, could you open a PR adding the line you mentioned? This way, the contribution will also be properly attributed to you 👍

**Comment by nijlandvpr** [comment]
Done!

**Comment by AdrianMrn** [comment]
Thanks a lot!
