### ISSUE TITLE
Can't update from 1.18.4 to 1.18.5

### ISSUE THREAD

**Issue by noge075** [spatie/ray#596]
Hello!
I got the update available message from Ray (windows) application as usual, but now If I restart the application and the install process finished, I always get the same update available message.

As you can see on the image, the version stays on 1.18.4. 

**Versions**
Ray version (you can see this in "About Ray"): 1.18.4.0

**To Reproduce**
1. Click on "Restart" button in "Application Update" window.
2. Wait until the installation finish.
3. 
**Expected behavior**
Successfuly update to the new version.

**Screenshots**
![image](https://user-images.githubusercontent.com/16837514/142423893-60a9cc24-e6ba-4ed2-955a-fbc726602076.png)
![image](https://user-images.githubusercontent.com/16837514/142423940-722aadc4-9368-4a7d-8d28-a5213bebb444.png)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by underdpt** [comment]
Hello,

To add more info, this also happens when installing from the download page. You download version 1.18.5 but when you launch it, the update message appears, and also it shows version 1.18.4.0 on "About Ray" menu option. 

Finally, on the release notes page there's no mention of version 1.18.5.

**Comment by AdrianMrn** [comment]
@noge075 @underdpt Are you still experiencing this issue after the weekend? Could you try choosing `later` when the update dialog comes up, restart Ray a minute later, and see if that changes anything?

**Comment by underdpt** [comment]
Hello, 

I tried with your instructions, I'm sorry the issue still exists.

**Comment by AdrianMrn** [comment]
Could you please have a look where your application is installed and delete all the files, then download the app from the website again? It's possible that because of my error in 1.18.4 that 2 installations of the app exist on your system, which could be causing the issue.

The default install location on a Windows machine is (I believe) `C:\Users\yourname\AppData\Local\Programs`. Here, delete both the `Ray` and `ray-app` folders, then reinstall from the website and try again.

Sorry for the issues you're encountering, this is completely my bad 🙈

**Comment by underdpt** [comment]
Solved, thanks!

**Comment by AdrianMrn** [comment]
Great to hear, thanks for your patience!
