### ISSUE TITLE
Colorblind Buttons not visible

### ISSUE THREAD

**Issue by vicenterusso** [spatie/ray#656]
**Describe the bug**
Color blind buttons not visible on version 2

**Versions**
Ray version: 2

**Screenshots**
![image](https://user-images.githubusercontent.com/80538/158820622-bf453122-838f-49f5-8e92-c75b3d5fe19d.png)

**Desktop (please complete the following information):**
 - OS: Linux

**Comment by willemvb** [comment]
Fixed for next release!

- On MacOS I now truncate with a little mask, since space is very limited.

<img width="424" alt="image" src="https://user-images.githubusercontent.com/1336390/159459143-dd8b7f1b-ede2-414d-b373-e26259411ec1.png">

- Especially `green` and `gray` could be confusing truncated, so tooltips to the rescue here: 

<img width="149" alt="image" src="https://user-images.githubusercontent.com/1336390/159459013-5e9e32d7-0e1d-493b-811e-3a3e03a730c0.png">

- `Clear all` only shows when there's more vertical room.

<img width="266" alt="image" src="https://user-images.githubusercontent.com/1336390/159459467-e3ec645e-2194-4492-8243-ad9ee8b0de0b.png">
