### ISSUE TITLE
wsl and laravel

### ISSUE THREAD

**Issue by spham** [spatie/ray#756]
**Describe the bug**
event not return from test

**Versions**
2.1.1.0

You can use `composer show` to get the version numbers of:
- spatie/ray package version:
- spatie/laravel-ray package version (if applicable): 

PHP version:
Laravel version (if applicable):

**To Reproduce**

step0: publish config

step1: update .env

```
RAY_HOST=
RAY_REMOTE_PATH=
RAY_LOCAL_PATH=
```

start a t, it's not work 

**Expected behavior**
display result

**Desktop (please complete the following information):**
 - OS: Debian 11 WSL2 on Windows 10
 - Version

**Comment by RhysLees** [comment]
To get this to work on wsl2 you will need to do the following:

Add this to your wsl2 terminal profile, in my case `~/.bashrc`:

```bash
# Set winhost to windows ip
export winhost=$(cat /etc/resolv.conf | grep nameserver | awk '{ print $2 }')
old_winhost=$(grep -P "[[:space:]]winhost" /etc/hosts | awk '{ print $1 }')

if [ -z $old_winhost ]; then
    echo "write winhost to /etc/hosts"
    echo "$winhost winhost" | sudo tee -a "/etc/hosts"
elif [ $old_winhost != $winhost ]; then
    echo "update winhost in /etc/hosts from $old_winhost to $winhost"
    sudo sed -i "s/$old_winhost winhost/$winhost winhost/g" /etc/hosts
fi
```

Close and restart your terminal

This will then when a new terminal is opened create an entry in wsl2's hosts file a `winhost` config pointing to windows local ip.

The reason you have to do this is because windows local ip for wsl changes every time wsl2 is started/restarted.

In your projects env add `RAY_HOST=winhost`

This will also work for Helo and other windows applications as `winhost` is basically the same as localhost except referring to windows compared to `localhost` referring to wsl2

**Comment by spham** [comment]
too complcated for me

**Comment by RhysLees** [comment]
> too complcated and overkill for me

it only takes 30 seconds to do...
